scrape_configs:
  - job_name: 'microservices-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:8080','host.docker.internal:8081','host.docker.internal:8082']